import streamlit as st
import sys
import os
import uuid
import datetime
from langchain_core.messages import HumanMessage, AIMessage

# Add project root to sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# NOTE: Moved import down to avoid crashing if env vars are missing at startup
# from chattutor.core.agent_builder_v2 import build_agent 

# --- Streamlit Config ---
st.set_page_config(page_title="ChatTutor", page_icon="🎓")

# Hide default menu
hide_menu_style = """
        <style>
        #MainMenu {visibility: hidden;}
        </style>
        """
st.markdown(hide_menu_style, unsafe_allow_html=True)

st.title("🎓 ChatTutor AI")

# --- Initialization ---

@st.cache_resource
def get_graph():
    """Builds and caches the LangGraph agent."""
    # Check for API Key first to give a friendly error
    if not os.getenv("DEEPSEEK_API_KEY"):
         raise ValueError("DEEPSEEK_API_KEY environment variable is missing!")
    
    # Lazy import to avoid top-level crash
    from chattutor.core.agent_builder_v2 import build_agent
    return build_agent()

try:
    graph = get_graph()
except Exception as e:
    st.error(f"❌ 初始化失败: {e}")
    st.info("请在 ModelScope 创空间的「设置 -> 环境变量」中配置 DEEPSEEK_API_KEY。")
    st.stop()

# Initialize Session State
if "messages" not in st.session_state:
    st.session_state.messages = []

if "session_id" not in st.session_state:
    st.session_state.session_id = f"{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_{str(uuid.uuid4())[:4]}"

if "agent_state_context" not in st.session_state:
    # storing persistent context parts of AgentState
    st.session_state.agent_state_context = {
        "current_topic": "General Knowledge",
        "conversation_summary": None,
        "summarized_msg_count": 0
    }

# --- Sidebar ---
with st.sidebar:
    st.header("Debug Info")
    st.write(f"**Session ID:** {st.session_state.session_id}")
    if st.button("Clear History"):
        st.session_state.messages = []
        st.session_state.agent_state_context = {
            "current_topic": "General Knowledge",
            "conversation_summary": None,
            "summarized_msg_count": 0
        }
        st.rerun()

# --- Chat Interface ---

# Display chat history
for msg in st.session_state.messages:
    if isinstance(msg, HumanMessage):
        with st.chat_message("user"):
            st.markdown(msg.content)
    elif isinstance(msg, AIMessage):
        with st.chat_message("assistant"):
            st.markdown(msg.content)

# Handle user input
if user_input := st.chat_input("Ask your question..."):
    # 1. Display User Message
    with st.chat_message("user"):
        st.markdown(user_input)
    
    # 2. Add to history
    user_msg_obj = HumanMessage(content=user_input)
    
    # NOTE: We must ensure st.session_state.messages is up to date before creating state
    current_messages = st.session_state.messages + [user_msg_obj]
    st.session_state.messages = current_messages # Optimistic update

    # 3. Construct Agent State
    current_state = {
        "messages": current_messages, 
        "session_id": st.session_state.session_id,
        "current_topic": st.session_state.agent_state_context["current_topic"],
        "conversation_summary": st.session_state.agent_state_context.get("conversation_summary"),
        "summarized_msg_count": st.session_state.agent_state_context.get("summarized_msg_count", 0),
        # Initialize other fields
        "plan": None,
        "tutor_output": None,
        "judge_output": None,
        "inquiry_output": None,
        "summary_output": None,
        "should_exit": False,
        "last_intent": None
    }

    # 4. Invoke Agent
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                # The graph returns the updated state
                result_state = graph.invoke(current_state)
                
                # Extract the latest AI message
                all_messages = result_state["messages"]
                
                # We need to find the NEW messages generated by the AI
                # Since we passed `current_messages` as input, any message AFTER that length is new
                # But LangGraph might return a completely new list or just append. 
                # Usually it keeps the history.
                
                if all_messages:
                    last_msg = all_messages[-1]
                    if isinstance(last_msg, AIMessage):
                        st.markdown(last_msg.content)
                    
                    # Update session state with the FULL list from the Agent
                    # This ensures we capture any intermediate tool messages or corrections
                    st.session_state.messages = all_messages
                    
                    # Update context 
                    st.session_state.agent_state_context["current_topic"] = result_state.get("current_topic")
                    st.session_state.agent_state_context["conversation_summary"] = result_state.get("conversation_summary")
                    st.session_state.agent_state_context["summarized_msg_count"] = result_state.get("summarized_msg_count", 0)
                    
            except Exception as e:
                st.error(f"Error during processing: {e}")
